name: 'Push message'
description: 'Push message to specified user'
branding:
  icon: 'message-square'
  color: 'blue'
inputs:
  server:
    description: 'Which server to be used to push message'
    required: true
    default: 'QYWX'
  message:
    description: 'Message'
    required: true
    default: 'Hello world'

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.server }}
    - ${{ inputs.message }}
